const fs = require("fs");
const path = require("path");
require("dotenv").config();

const template = fs.readFileSync("./src/template.html", "utf8");

// This is the funtion to create a dist folder
// To store the index.html after executing build.js script
if(!fs.existsSync("./dist/")){
  fs.mkdirSync("./dist/")
}

// To update the version of the app each time by one 


const html = template
  .replace("{{title}}", "My Static Site")
  .replace("{{header}}", "Generated by Node.js Multistage Build")
  .replace("{{buildTime}}", new Date().toISOString())
  .replace("{{version}}", process.env.APP_VERSION || "dev");

fs.writeFileSync("./dist/index.html", html);

console.log("index.html generated!");
